# Generated by Django 3.2.7 on 2021-11-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_vote_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
    ]
